version: '3.9'

services:
  reciminder-web:
    image: evanmccaleb59/reciminder-web:0.0.0-dev.3
    env_file:
      - prod.env
    command: bash -c "python Django/manage.py migrate && python Django/manage.py runserver 0.0.0.0:8987"
    ports:
      - "8987:8987"

  postgres-reciminder:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - prod_env