# Generated by Django 5.1.4 on 2024-12-29 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('06771c8b-ac51-7023-8000-2eac71c9afb1'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description_free_text', models.TextField(blank=True, null=True)),
                ('ingredients_free_text', models.TextField(blank=True, null=True)),
                ('Instructions_free_text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_by_user', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
