# Generated by Django 5.1.4 on 2024-12-29 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_instructions_free_text_recipe_instructions_free_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings_per_nominal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01941493-b8b7-7222-835d-634a111ccec3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
