# Generated by Django 5.1.4 on 2025-01-26 02:20

import django.utils.timezone
import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.recipe_images),
        ),
    ]
